import { secureHeaders } from "hono/secure-headers";

export function createManagementSecurityMiddleware() {
  return secureHeaders({
    contentSecurityPolicy: {
      defaultSrc: ["'none'"],
      baseUri: ["'none'"],
      connectSrc: ["'self'"],
      fontSrc: ["'self'"],
      formAction: ["'self'"],
      frameAncestors: ["'none'"],
      imgSrc: ["'self'"],
      objectSrc: ["'none'"],
      scriptSrc: ["'self'"],
      styleSrc: ["'self'"],
      styleSrcAttr: ["'unsafe-inline'"],
      styleSrcElem: ["'self'", "'unsafe-inline'"],
    },
    crossOriginEmbedderPolicy: false,
    crossOriginOpenerPolicy: "same-origin",
    crossOriginResourcePolicy: "same-origin",
    originAgentCluster: false,
    permissionsPolicy: {
      accelerometer: [],
      attributionReporting: [],
      autoplay: [],
      camera: [],
      chUa: [],
      chUaArch: [],
      chUaBitness: [],
      chUaFullVersion: [],
      chUaFullVersionList: [],
      chUaMobile: [],
      chUaModel: [],
      chUaPlatform: [],
      chUaPlatformVersion: [],
      chUaWow64: [],
      clipboardRead: [],
      clipboardWrite: [],
      computePressure: [],
      crossOriginIsolated: [],
      displayCapture: [],
      encryptedMedia: [],
      fullscreen: [],
      gamepad: [],
      geolocation: [],
      gyroscope: [],
      hid: [],
      identityCredentialsGet: [],
      idleDetection: [],
      keyboardMap: [],
      magnetometer: [],
      microphone: [],
      midi: [],
      payment: [],
      pictureInPicture: [],
      publickeyCredentialsGet: [],
      screenWakeLock: [],
      serial: [],
      storageAccess: [],
      syncXhr: [],
      usb: [],
      windowManagement: [],
      xrSpatialTracking: [],
    },
    referrerPolicy: "no-referrer",
    strictTransportSecurity: false,
    xContentTypeOptions: "nosniff",
    xDnsPrefetchControl: "off",
    xDownloadOptions: false,
    xFrameOptions: "DENY",
    xPermittedCrossDomainPolicies: false,
    xXssProtection: false,
  });
}
